### ISSUE TITLE
I have problem to use the software in linux 

### ISSUE THREAD

**Issue by lrj-1** [BGI-shenzhen/LDBlockShow#3]
$ LDBlockShow   -InVCF 507sample.vcf_Chr_id.vcf -OutPut file -Region chr14:55370544:55870544 -OutPng
#Detected VCF File is phased file with '|', Read VCF in Phase mode
		InPut Para -Region  chromosome [chr14]  can't be found in the SNP dataset
Warining: SVG module in Perl is missing, trying to loading the built-in [SVG.pm]...
Loading SVG module done
Start draw... SVG info: SNPNumber :0 , SVG (width,height) = (0,0)
Use of uninitialized value in subtraction (-) at /public/home/yplu/biosoft/LDBlockShow-1.36/bin//ShowLDSVG line 510, <IB> line 1.
Use of uninitialized value in subtraction (-) at /public/home/yplu/biosoft/LDBlockShow-1.36/bin//ShowLDSVG line 510, <IB> line 1.
Use of uninitialized value in subtraction (-) at /public/home/yplu/biosoft/LDBlockShow-1.36/bin//ShowLDSVG line 532, <IB> line 1.
Use of uninitialized value in subtraction (-) at /public/home/yplu/biosoft/LDBlockShow-1.36/bin//ShowLDSVG line 532, <IB> line 1.
Illegal division by zero at /public/home/yplu/biosoft/LDBlockShow-1.36/bin//ShowLDSVG line 532, <IB> line 1.

**Comment by hewm2008** [comment]
It may be caused by the one of  following two reasons
reasons A: The region you gave has no snp sites (or the region has no snp after filtering such as maf). If so, you can enlarge the region. 
reasons B: You gave the wrong chr name. First, make sure if the chr name is right . Give the correct chr name, which must be consistent with the chr name of the VCF file.

有可能是如下两个原因造成的 
 A :你给的这个region没有snp位点 （or 被过滤掉了   如maf 等过滤后 这个region一个snp都没有），若是这样可以把region放大     B：你给错了 chr名字  。  你先确认一下是不是chr名给错了，给对的chr名，要和VCF文件的chr名是一致的。

**Comment by lrj-1** [comment]
thanks for your timely reply ,and  I check name,but it have new number
svg can't convert to png


convert   SVG ---> PNG ...
which: no convert in (/public/home/yplu/perl5/bin:/public/home/yplu/miniconda3/bin:/public/home/yplu/miniconda3/condabin:/public/home/yplu/myBin/bin:/public/home/software/opt/moudles/Modules/3.2.10/bin:/opt/ibm/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/public/home/yplu/.local/bin:/public/home/yplu/bin)
Can't find the [ convert ] bin, I try to convert svg by /public/home/yplu/biosoft/LDBlockShow-1.36/bin/svg_kit/svg2xxx.pl

**Comment by hewm2008** [comment]
This is just a warning and does not affect the results, mainly in the step of converting svg to png.
reason : Your system does not have this command [ **convert** ] command
solution ： you can install it[**convert**] yourself.

Because there is no such [convert] command on yours linux , the program calls [LDBlockShow-1.36/bin/svg_kit/svg2xxx.pl] to convert svg to png or pdf

这个只是提示而己，并不影响结果，主要在转化svg到png这一步。
原因是： 你的系统没有这个命令   convert 的命令，
解决 ： 你可以自己安装之。
or   由于没有这个命令，程序调用了   LDBlockShow-1.36/bin/svg_kit/svg2xxx.pl  把svg转为png  or  pdf

**Comment by dawei1203** [comment]
yum install ImageMagick
