### ISSUE TITLE
chromosome region can't be found in the input dataset

### ISSUE THREAD

**Issue by TZM9882** [BGI-shenzhen/LDBlockShow#34]
Dear developer,

I am new to using packages and tools.

First of all, thank you for this tool. It looks simple. But, I couldn't get any expected outputs after trying many attempts as much as I could. When I used test files from Example folder, I can get as recommended. But with my file, always showed the following message in that attached image.

Please check and help me with this problem.

thanks,

![Screenshot 2023-06-26 at 11 36 14](https://github.com/BGI-shenzhen/LDBlockShow/assets/129658757/49dc7930-e695-43c1-9c91-d88745fe7b5f)

**Comment by hewm2008** [comment]
you can see more help (SNP filter parameters) by follow command:
./bin/LDBlockShow -h
The 8 SNPs after filtering as follows "-MAF 0.05 -Het 0.90 -Miss 0.25" remain 0 SNPs . you can modify these three parameters according to your own situation.

Other info :
A ：The soft will skip non bi-allelic(Singleton/ThreeMulti allelic) site and indel site (For bi-allelic indel, you can modify the "REF ALT" to only one base. see the Perl script at the end of this conversation
B： I guess it is caused by the wrong region of ​​your input. Someone often make mistakes in the upper or lower characters of chr name [chr3/ Chr3 / 3/], please make sure that the chr name you input is consistent with vcf input file ,If the chr name is the same, you can enlarge the region ,so that there is a certain amount of snp in this region.

**Comment by TZM9882** [comment]
the problem was caused by B. (chromosome name, it was coded by "6")
thank you for your quick suggestion.
