### ISSUE TITLE
Argument "" isn't numeric in log at /LDBlockShow/bin//ShowLDSVG line 999

### ISSUE THREAD

**Issue by frucelee** [BGI-shenzhen/LDBlockShow#5]
Dear friends,
Thank you for the good software. When I tried this software for the first time, it shows the problem as follows,
command line:  ./LDBlockShow -InVCF est_vcf.vcf -OutPut gd -InGWAS GWASpvalue.txt    -InGFF LDBlockShow/Bos_taurus.ARS-UCD1.2.103.gff3.gz -Region 11:24000000:24200000 -OutPng -SeleVar 3
##Start Region Cal...    :11 24000000 24200000; In This Region TotalSNP Number is 7
find blocks...
Start draw... SVG info: SNPNumber :7 , SVG (width,height) = (455,518)
Argument "" isn't numeric in log at /LDBlockShow/bin//ShowLDSVG line 999.
Can't take log of 0 at /LDBlockShow/bin//ShowLDSVG line 999.

I try to find the reason, but it no success. Could you please give me some advice on that?
Best,
fruce

**Comment by hewm2008** [comment]
Dear @frucelee 
   the  code at lines 999: 
`	$MinP=0-sprintf ("%.2f",(log($MaxP)/log(10)));   `
The reason is that the **minimum value of pvalue in the gwas** of your input is **0**, and 0 cannot be used for log.
So it is the problem of the data of your input file. In theory, the pvalue of gwas cannot be 0. It is recommended that you change it to a minimum value such as 1e-10
